project:
  type: book
  output-dir: docs
  
book:
  title: Computational Statistics (M.Sc.)
  author: Prof. Dr. Dominik Liebl 
  search: true
  logo: images/Uni_Bonn_Logo.jpeg
  number-depth: 3
  chapters:
    - index.qmd
    - Ch1_Random_Variable_Generation.qmd  # Reads in Ch2_Solutions.qmd
    - Ch2_MonteCarlo.qmd
    - Ch3_Bootstrap.qmd
    - Ch4_MaximumLikelihood.qmd
    - Ch5_EMAlgorithmus.qmd
    - Ch6_NonparametricRegression.qmd

bibliography: references.bib

execute:
  cache: true

format:
  html:
    theme: cosmo