project:
  type: book
  output-dir: docs
  
book:
  title: Computational Statistics (M.Sc.)
  author: Prof. Dr. Dominik Liebl 
  date: last-modified
  date-format: "[Last Updated on] MMMM DD, YYYY"
  search: true
  logo: images/Uni_Bonn_Logo.jpeg
  number-depth: 3
  chapters:
    - index.qmd
    - Ch1_MaximumLikelihood.qmd
    - Ch2_EMAlgorithmus.qmd
    # - Ch3_Bootstrap.qmd
    #- Ch1_Random_Variable_Generation.qmd  
    #- Ch2_MonteCarlo.qmd                 # Reads in Ch2_Solutions.qmd
    #- Ch6_NPRegression.qmd
    #- Ch6_NonparametricRegression.qmd

bibliography: references.bib

execute:
  cache: true

format:
  html:
    theme: cosmo